### ISSUE TITLE
Error: Cannot find module 'openlayers/node_modules/closure-util'

### ISSUE THREAD

**Issue by eleu** [camptocamp/c2cgeoportal#2250]
while upgrading to GeoMapFish 1.6.8rc2:

Running `make ... build` now causes the following error multiple times:

```
WMTSCAPABILITIES_PATH=1.0.0/WMTSCapabilities-u207027.xml INSTANCE_ID=u207027 APACHE_ENTRY_POINT=/u207027/ DEVELOPMENT=FALSE PACKAGE=bl_gis2012 .build/venv/bin/c2c-template --vars vars_dev2.yaml --engine mako --files alembic_static.ini.mako

module.js:340
    throw err;
          ^
Error: Cannot find module 'openlayers/node_modules/closure-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:22
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
ERROR when running the expression ''process.stdout.write(require("openlayers/node_modules/closure-util").getLibraryPath())'': Command '['node', '-e', 'process.stdout.write(require("openlayers/node_modules/closure-util").getLibraryPath())']' returned non-zero exit status 8
```

The instance seems to work anyway (except in some special cases at BL).

**Comment by ochriste** [comment]
This message is "normal" when using a project not using ngeo.
See with @sbrunner

**Comment by sbrunner** [comment]
already fixed

**Comment by eleu** [comment]
@sbrunner for which version?

**Comment by sbrunner** [comment]
1.6.8

**Comment by eleu** [comment]
1.6.8 stable? or rc2 ? (we constated the problem in 1.6.8rc2).

**Comment by eleu** [comment]
yes 1.6.8 stable.

**Comment by marionb** [comment]
I am still getting this error after upgrading to 1.6.8 stable.

**Comment by svavoi** [comment]
I just tried to upgrade to 1.6.8 stable and I get the same error. Is there already a solution to this?

**Comment by yjacolin** [comment]
Same for Jura https://github.com/camptocamp/jura_c2cgeoportal/issues/63

**Comment by rbovard** [comment]
So we cannot build `1.6.8`?

**Comment by yjacolin** [comment]
You can but you get some errors in the log. Here is a workaround: comment this line

```
    # FIXME: Workaround to avoid error messages during build (issue #103)
    # node:
    #     vars:
    #     - closure_library_path
    #     cmd: ["node", "-e"]
    #     ignore_error: true
```

**Comment by rbovard** [comment]
Ok, thanks @yjacolin

**Comment by jwkaltz** [comment]
A new ticket has been opened for the same issue: https://github.com/camptocamp/c2cgeoportal/issues/3091
I am therefore closing this one.
