### ISSUE TITLE
[Upgrade to 1.6] JavaScript issues

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#1525]
Since #1524 is fixed, I have now JS and missing files issues:

````
Uncaught TypeError: Cannot read property 'prototype' of undefined
Uncaught TypeError: OpenLayers.Control.Navigation is not a function
GET http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/defs/EPSG21781.js 
GET http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/projCode/somerc.js 
````

I don't know if it's related to my project or the upgrade process since it's the first time I can "see" my project in 1.6...

You can see the errors here http://nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net/

**Comment by sbrunner** [comment]
You miss OpenLayers.Control.DrawFeature in your @include of your file RasterStatistic.js :-)

**Comment by rbovard** [comment]
Hum strange because it works fine in 1.5...

How did you arrived to this conclusion, because I added it and there is still the error message (currently I removed)?

**Comment by sbrunner** [comment]
I install your application in my home to debug it, ...., `OpenLayers.Control.DrawFeature` will be undefined and required in `RasterStatistic.js`

**Comment by rbovard** [comment]
Ok I see... But how do you know there was an issue there (to learn how to debug this issue)?

**Comment by sbrunner** [comment]
The documentations is here http://docs.camptocamp.net/c2cgeoportal/1.6/developer/debugging.html, but it's not easy to find this kind of issue ...

**Comment by rbovard** [comment]
Ok, thanks a lot @sbrunner!
