### ISSUE TITLE
External WMTS background layer

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2380]
Is it possible to have external WMTS background layer (in my case ASIT VD)?

Because when getting the themes I have a 500 error:

```
URL: wsgi/themes?version=2&background=background
File '.build/venv/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
  return self.app(environ, start_response)
File '.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '.build/venv/lib/python2.7/site-packages/webob/request.py', line 1317 in send
  application, catch_exc_info=False)
File '.build/venv/lib/python2.7/site-packages/webob/request.py', line 1281 in call_application
  app_iter = application(self.environ, start_response)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 223 in __call__
  response = self.invoke_subrequest(request, use_tweens=True)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 198 in invoke_subrequest
  response = handle_request(request)
File '.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/cacheversion.py', line 62 in __call__
  response = self.handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid/tweens.py', line 20 in excview_tween
  response = handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 101 in tm_tween
  reraise(*exc_info)
File '.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 83 in tm_tween
  response = handler(request)
File '.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 145 in handle_request
  view_name
File '.build/venv/lib/python2.7/site-packages/pyramid/view.py', line 541 in _call_view
  response = view_callable(context, request)
File '.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 353 in rendered_view
  result = view(context, request)
File '.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 483 in _class_requestonly_view
  response = getattr(inst, attr)()
File '.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 1358 in themes
  result["background_layers"] = group["children"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by gnerred** [comment]
By my side, I have this error with asit background. I think there is something to configure on asit side ? 

XMLHttpRequest cannot load https://ows.asitvd.ch/wmts?service=wmts&request=getcapabilities. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://preprod.cartoriviera.ch' is therefore not allowed access.

**Comment by fredj** [comment]
@gnerred yes, they need to add the CORs HTTP header: http://enable-cors.org/

**Comment by gnerred** [comment]
Thanks @fredj . What is strange, is that the desktop version does not have this problem : 

https://preprod.cartoriviera.ch/v2/mobile/ -> problem
https://preprod.cartoriviera.ch/v2/ -> no problem

Something to configure on GMF side ?

**Comment by gnerred** [comment]
Okay, it seems that ASIT-VD can do something. I will come back as soon as I have news.

**Comment by gnerred** [comment]
ASIT-VD has done the necessary, now it work for me 
https://preprod.cartoriviera.ch/v2/mobile/theme/cadastre?lang=fr&baselayer_ref=asitvd.fond_gris

**Comment by sbrunner** [comment]
@rbovard  Don't you miss to check the interface in the base layers?

**Comment by sbrunner** [comment]
Is it working on 2.1?

**Comment by sbrunner** [comment]
Is it working on 2.1?

**Comment by sbrunner** [comment]
Is it working on 2.1?

**Comment by gnerred** [comment]
It already worked for me in 2.0 (see my last comment)

**Comment by sbrunner** [comment]
OK, thanks, I close it :-)
